extern const unsigned char PROGMEM soldiers[], soldiers_mask[];
extern const unsigned char PROGMEM tiles[];
extern const unsigned char PROGMEM boss[], boss_mask[];
extern const unsigned char PROGMEM hair6[], hair6_mask[];
extern const unsigned char PROGMEM bg[], bg_mask[];
extern const unsigned char PROGMEM hair5[], hair5_mask[];
extern const unsigned char PROGMEM hair4[], hair4_mask[];
extern const unsigned char PROGMEM hair3[], hair3_mask[];
extern const unsigned char PROGMEM hair2[], hair2_mask[];
extern const unsigned char PROGMEM hair1[], hair1_mask[];
extern const unsigned char PROGMEM eyes5[], eyes5_mask[];
extern const unsigned char PROGMEM eyes4[], eyes4_mask[];
extern const unsigned char PROGMEM eyes3[], eyes3_mask[];
extern const unsigned char PROGMEM eyes2[], eyes2_mask[];
extern const unsigned char PROGMEM eyes1[], eyes1_mask[];
extern const unsigned char PROGMEM ears5[], ears5_mask[];
extern const unsigned char PROGMEM ears4[], ears4_mask[];
extern const unsigned char PROGMEM ears3[], ears3_mask[];
extern const unsigned char PROGMEM ears2[], ears2_mask[];
extern const unsigned char PROGMEM ears1[], ears1_mask[];
extern const unsigned char PROGMEM base1[], base1_mask[];
extern const unsigned char PROGMEM acc6[], acc6_mask[];
extern const unsigned char PROGMEM acc5[], acc5_mask[];
extern const unsigned char PROGMEM acc4[], acc4_mask[];
extern const unsigned char PROGMEM acc3[], acc3_mask[];
extern const unsigned char PROGMEM acc2[], acc2_mask[];
extern const unsigned char PROGMEM acc1[], acc1_mask[];

